# Generated by Django 5.2.6 on 2025-09-19 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapprovallog",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_approval_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentapprovallog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_logs",
                to="profiles.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studenttopuplog",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_topup_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studenttopuplog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topup_logs",
                to="profiles.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["is_approved"], name="studprof_approved_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["type"], name="studprof_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)), name="studprof_balance_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_approved", True), ("type", "offline")),
                    models.Q(("is_approved", False), ("type", "online")),
                    _connector="OR",
                ),
                name="studprof_type_matches_approval",
            ),
        ),
        migrations.AddIndex(
            model_name="studentapprovallog",
            index=models.Index(fields=["created_at"], name="studapprlog_created_idx"),
        ),
        migrations.AddIndex(
            model_name="studentapprovallog",
            index=models.Index(fields=["approved"], name="studapprlog_approved_idx"),
        ),
        migrations.AddIndex(
            model_name="studenttopuplog",
            index=models.Index(fields=["created_at"], name="studtopuplog_created_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(fields=["created_at"], name="teachprof_created_idx"),
        ),
    ]
