# Generated by Django 5.2.6 on 2025-09-19 18:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True, null=True)),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("register", "Register"), ("login", "Login")],
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "verification_codes",
                "indexes": [
                    models.Index(
                        fields=[
                            "telegram_id",
                            "purpose",
                            "consumed",
                            "expires_at",
                            "created_at",
                        ],
                        name="vc_tid_purp_cons_exp_cre_idx",
                    ),
                    models.Index(
                        fields=[
                            "telegram_username",
                            "purpose",
                            "consumed",
                            "expires_at",
                            "created_at",
                        ],
                        name="vc_tuser_purp_cons_exp_cre_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "^\\d{6}$")),
                        name="verification_code_six_digits",
                    )
                ],
            },
        ),
    ]
