# Generated by Django 5.2.6 on 2025-09-20 18:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tests", "0007_alter_answersubmission_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "price_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to="tests.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_tests",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_answer", models.JSONField(blank=True, null=True)),
                ("is_correct", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="tests.question",
                    ),
                ),
                (
                    "user_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="user_tests.usertest",
                    ),
                ),
            ],
            options={
                "db_table": "user_answers",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("listening_score", models.FloatField(blank=True, null=True)),
                ("reading_score", models.FloatField(blank=True, null=True)),
                ("writing_score", models.FloatField(blank=True, null=True)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, default="")),
                ("errors_analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="user_tests.usertest",
                    ),
                ),
            ],
            options={
                "db_table": "test_results",
            },
        ),
        migrations.AddIndex(
            model_name="usertest",
            index=models.Index(fields=["user", "status"], name="ut_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="usertest",
            index=models.Index(fields=["created_at"], name="ut_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="usertest",
            constraint=models.UniqueConstraint(
                fields=("user", "test"), name="uniq_user_test_once"
            ),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["user_test"], name="ua_user_test_idx"),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["question"], name="ua_question_idx"),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("user_test", "question"), name="uniq_answer_per_question"
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["overall_score"], name="tr_overall_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["created_at"], name="tr_created_idx"),
        ),
    ]
