# Generated by Django 5.2.6 on 2025-09-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0007_alter_answersubmission_unique_together_and_more"),
        ("user_tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllTestsProxy",
            fields=[],
            options={
                "verbose_name": "All test",
                "verbose_name_plural": "All tests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tests.test",),
        ),
        migrations.AlterModelOptions(
            name="testresult",
            options={
                "verbose_name": "Result review",
                "verbose_name_plural": "Result reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={"verbose_name": "Answer", "verbose_name_plural": "Answers"},
        ),
        migrations.AlterModelOptions(
            name="usertest",
            options={"verbose_name": "My test", "verbose_name_plural": "My tests"},
        ),
    ]
