# Generated by Django 5.2.6 on 2025-09-20 18:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_tests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[("task1", "Task 1"), ("task2", "Task 2")],
                        max_length=10,
                    ),
                ),
                ("submitted_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("in_checking", "In checking"),
                            ("checked", "Checked"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, default="")),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taken_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_submissions",
                        to="user_tests.usertest",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_submissions",
                "indexes": [
                    models.Index(fields=["status"], name="ts_status_idx"),
                    models.Index(
                        fields=["teacher", "status"], name="ts_teacher_status_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_test", "task"), name="uniq_submission_per_task"
                    )
                ],
            },
        ),
    ]
