# Generated by Django 5.2.6 on 2025-09-22 17:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Created")],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UZS", max_length=3)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_requests",
                        to="profiles.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "speaking_requests",
                "indexes": [
                    models.Index(
                        fields=["student", "status"], name="spreq_student_status_idx"
                    ),
                    models.Index(fields=["created_at"], name="spreq_created_idx"),
                ],
            },
        ),
    ]
