# Generated by Django 5.2.6 on 2025-10-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="error_note",
            field=models.TextField(blank=True, default="", max_length=255),
        ),
    ]
