# Generated by Django 5.2.6 on 2025-09-19 18:05

import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fullname", models.CharField(max_length=100)),
                (
                    "telegram_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Stored lowercased; unique (case-insensitive) when not null.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Superadmin"),
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_activity",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="cdi_users", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="cdi_user_perms", to="auth.permission"
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["phone_number"], name="users_phone_idx"),
                    models.Index(fields=["role"], name="users_role_idx"),
                    models.Index(fields=["telegram_id"], name="users_tgid_idx"),
                    models.Index(fields=["created_at"], name="users_created_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("phone_number__regex", "^\\+?[1-9]\\d{7,14}$")
                        ),
                        name="users_phone_e164_like",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fullname", ""), _negated=True),
                        name="users_fullname_not_empty",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("telegram_username"),
                        condition=models.Q(("telegram_username__isnull", False)),
                        name="users_tg_username_ci_uniq",
                    ),
                ],
            },
        ),
    ]
