# Generated by Django 5.2.6 on 2025-09-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListeningSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "mp3_file",
                    models.FileField(blank=True, null=True, upload_to="listening/mp3/"),
                ),
            ],
            options={
                "verbose_name": "Listening section",
                "verbose_name_plural": "Listening sections",
                "db_table": "listening_section",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Main question text shown to the student."
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("R_YES_NO_NOT_GIVEN", "Reading: Yes/No/Not Given"),
                            ("R_TRUE_FALSE_NOT_GIVEN", "Reading: True/False/Not Given"),
                            ("R_MULTIPLE_CHOICE", "Reading: Multiple Choice"),
                            ("R_MATCHING_INFORMATION", "Reading: Matching Information"),
                            ("R_MATCHING_HEADINGS", "Reading: Matching Headings"),
                            ("R_MATCHING_FEATURES", "Reading: Matching Features"),
                            (
                                "R_MATCHING_SENTENCE_ENDINGS",
                                "Reading: Matching Sentence Endings",
                            ),
                            ("R_SENTENCE_COMPLETION", "Reading: Sentence Completion"),
                            ("R_SUMMARY_COMPLETION", "Reading: Summary Completion"),
                            ("R_SHORT_ANSWER", "Reading: Short Answer"),
                            ("R_DIAGRAM_COMPLETION", "Reading: Diagram Completion"),
                            ("L_MULTIPLE_CHOICE", "Listening: Multiple Choice"),
                            ("L_MATCHING_HEADINGS", "Listening: Matching Headings"),
                            ("L_DIAGRAM_LABELLING", "Listening: Diagram Labelling"),
                            ("L_FORM_COMPLETION", "Listening: Form Completion"),
                            ("L_SENTENCE_COMPLETION", "Listening: Sentence Completion"),
                            ("L_SHORT_ANSWER", "Listening: Short Answer"),
                        ],
                        default="R_YES_NO_NOT_GIVEN",
                        help_text="Select the type (prefixed with R_ or L_).",
                        max_length=50,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="List of option objects (if applicable).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="TaskTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Task Two",
                "verbose_name_plural": "Task Two",
                "db_table": "task_two",
            },
        ),
        migrations.CreateModel(
            name="Listening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Listening", max_length=127)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sections", models.ManyToManyField(to="tests.listeningsection")),
            ],
            options={
                "verbose_name": "Listening",
                "verbose_name_plural": "Listenings",
                "db_table": "listening",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="QuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the question set (e.g., 'Reading Passage 1 MCQ').",
                        max_length=127,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text="Questions included in this set (aim for 10–15).",
                        related_name="sets",
                        to="tests.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question set",
                "verbose_name_plural": "Question sets",
            },
        ),
        migrations.AddField(
            model_name="listeningsection",
            name="questions_set",
            field=models.ManyToManyField(to="tests.questionset"),
        ),
        migrations.CreateModel(
            name="ReadingPassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("passage", models.TextField()),
                ("questions_set", models.ManyToManyField(to="tests.questionset")),
            ],
            options={
                "verbose_name": "Reading passage",
                "verbose_name_plural": "Reading passages",
                "db_table": "reading_passage",
            },
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Reading", max_length=127)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("passages", models.ManyToManyField(to="tests.readingpassage")),
            ],
            options={
                "verbose_name": "Reading",
                "verbose_name_plural": "Readings",
                "db_table": "reading",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TaskOne",
            fields=[
                (
                    "tasktwo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tests.tasktwo",
                    ),
                ),
                ("image_title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="task_one_images/")),
            ],
            options={
                "verbose_name": "Task One",
                "verbose_name_plural": "Task Ones",
                "db_table": "task_one",
            },
            bases=("tests.tasktwo",),
        ),
        migrations.CreateModel(
            name="Writing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writings_as_task_two",
                        to="tests.tasktwo",
                    ),
                ),
                (
                    "task_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writings_as_task_one",
                        to="tests.taskone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests.listening",
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.reading"
                    ),
                ),
                (
                    "writing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.writing"
                    ),
                ),
            ],
            options={
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
                "db_table": "test_table",
                "ordering": ["created_at"],
            },
        ),
    ]
