# Generated by Django 5.2.6 on 2025-09-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_alter_test_listening_alter_test_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="writing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tests.writing",
            ),
        ),
    ]
