# Generated by Django 5.2.6 on 2025-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0003_alter_test_writing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskone",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="task_one_images/"
            ),
        ),
        migrations.AlterField(
            model_name="taskone",
            name="image_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
