# Generated by Django 5.2.6 on 2025-09-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_alter_taskone_image_alter_taskone_image_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="table",
            field=models.JSONField(
                blank=True, default=dict, help_text="Table of question data.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of option objects (if applicable).",
                null=True,
            ),
        ),
    ]
