# Generated by Django 5.2.6 on 2025-09-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0006_answerrule_questionoption_testattempt_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answersubmission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="answersubmission",
            name="attempt",
        ),
        migrations.RemoveField(
            model_name="answersubmission",
            name="chosen_option",
        ),
        migrations.RemoveField(
            model_name="answersubmission",
            name="question",
        ),
        migrations.RemoveField(
            model_name="questionoption",
            name="question",
        ),
        migrations.RemoveField(
            model_name="testattempt",
            name="test",
        ),
        migrations.RemoveField(
            model_name="testattempt",
            name="user",
        ),
        migrations.DeleteModel(
            name="AnswerRule",
        ),
        migrations.DeleteModel(
            name="AnswerSubmission",
        ),
        migrations.DeleteModel(
            name="QuestionOption",
        ),
        migrations.DeleteModel(
            name="TestAttempt",
        ),
    ]
