# Generated by Django 5.2.6 on 2025-09-22 15:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0007_alter_answersubmission_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_dict",
            field=models.JSONField(
                blank=True, default=dict, help_text="Answer key data.", null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_list",
            field=models.JSONField(
                blank=True, default=list, help_text="Answer key data.", null=True
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="price",
            field=models.DecimalField(
                db_default=Decimal("0.00"), decimal_places=2, max_digits=12
            ),
        ),
    ]
