# Generated by Django 5.2.6 on 2025-09-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0008_question_answer_dict_question_answer_list_test_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listeningsection",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
